### ISSUE TITLE
dashboard.strn node error reporting multiple issues

### ISSUE THREAD

**Issue by KlausGlueckert** [filecoin-saturn/L1-node#330]
- all nodes in my region receive a lot of 502 and 504 errors increasing health check penalties and high TTFB.
- on the dashboard there is an "invalid date" bug

**example:**

`
Health Check Failures
Invalid Date Invalid DateNon OK response received: 504 Gateway Timeout fetching https://152.xxx.xxx.130/ipfs/bafybeiezqu4s4jatnjwnzojh3jiz2ihzqsn7lkoiltxg5ppipm4oqbpi2a/hidden.json?clientId=9c78cb9e-b9af-457c-b745-f9535b25a711&depth=0&format=car
Invalid Date Invalid DateNon OK response received: 504 Gateway Timeout fetching https://152.xxx.xxx.130/ipfs/bafybeibwhfzarhbns2ftusrezl6jllu7rqzvk3alcti3lesdtfbvabx37y/AIOZNFT_1668671925946.jpg?clientId=ecb03799-8453-4647-bd92-afb8f51a7fcf&depth=0&format=car
Invalid Date Invalid DateNon OK response received: 502 Bad Gateway fetching https://152.xxx.xxx.130/ipfs/bafybeie76qpgaw25nf7wib2btrqvpc3rjtdhkwzi7kzan7np5wyx7y3mry/metadata.json?clientId=e953f614-2ac3-464a-8d19-dc85bfbf96f6&depth=0&format=car
`

**Comment by DiegoRBaquero** [comment]
This should be fixed

**Comment by KlausGlueckert** [comment]
Issue is not fixed. Still showing "Invalid Date"

`Health Check Failures
Invalid Date Invalid Daterequest to https://152.xxx.xxx.130/ipfs/QmYsTqbmGA3H5cgouCkh8tswJAQE1AsEko9uBZX9jZ3oTC/twinkle.json?clientId=d6bf5382-5404-49db-a5a7-dfce813ba500&car-scope=file&format=car failed, reason: connect ECONNREFUSED 152.xxx.xxx.130:443
Invalid Date Invalid Date152.xxx.xxx.130 connection timed out after 4 retries
Invalid Date Invalid Date152.xxx.xxx.130 connection timed out after 4 retries`
